### ISSUE TITLE
GPT-4 Vision supports functions now

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-extract#19]
https://twitter.com/OpenAIDevs/status/1777769463258988634

> GPT-4 Turbo with Vision is now generally available in the API. Vision requests can now also use JSON mode and function calling.
https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4

**Comment by simonw** [comment]
This means I can get rid of this horrible hack:

https://github.com/datasette/datasette-extract/blob/7429965988761ee7ee7ef645e88cd97e7c419622/datasette_extract/__init__.py#L284-L318

**Comment by simonw** [comment]
It worked against my test image:

![comedy-luau](https://github.com/datasette/datasette-extract/assets/9599/58de633a-fcff-41d3-afcb-e27e9984ffbf)

```json
[
  {
    "event_title": "Coastside Comedy Luau",
    "event_description": "Comedy event featuring Laurie Kilmartin, Ryan Goodcase, and Phil Griffiths, hosted by Marcus D. Includes Hawaiian buffet and welcome cocktail. Proceeds benefit Wilkinson School and Coastside Hope.",
    "event_date": "2022-05-06",
    "start_time": "18:00",
    "end_time": "22:00"
  }
]
```

![CleanShot 2024-04-09 at 12 08 25@2x](https://github.com/datasette/datasette-extract/assets/9599/c52481ef-2083-46c6-8903-2149f0753a3f)

**Comment by simonw** [comment]
Video demo: https://www.youtube.com/watch?v=g3NtJatmQR0

**Comment by brianjking** [comment]
Absolutely killing it, thank you, @simonw -- I've noticed some weird date issues with GPT-4 vision, wonder if that's what you saw in your demo video.
